import { relativeTime } from '../lib/format'
import type { SituationReport } from '../types'

export function ReportPanel({ report, now }: { report: SituationReport; now: number }) {
  return (
    <section className="panel panel--report">
      <header className="panel__head">
        <h2 className="panel__title">Situation report</h2>
        <span className="panel__meta">
          {report.generator === 'llm' ? (
            <>
              Generated by {report.model ?? 'Claude'}
              {report.reused && ' · reused, situation unchanged'}
            </>
          ) : (
            'Written by the rules engine (LLM unavailable)'
          )}
          {report.generated_at && ` · ${relativeTime(report.generated_at, now)}`}
        </span>
      </header>

      <h3 className="report__title">{report.situation_title}</h3>
      <p className="report__summary">{report.summary}</p>

      {report.operational_impact.length > 0 && (
        <div className="report__block">
          <h4 className="report__subtitle">What this means operationally</h4>
          <ul className="list">
            {report.operational_impact.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      )}

      {report.contributing_factors.length > 0 && (
        <div className="report__block">
          <h4 className="report__subtitle">Main factors</h4>
          <ul className="list">
            {report.contributing_factors.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="report__confidence">
        <span className={`confidence confidence--${report.confidence}`}>
          Confidence: {report.confidence}
        </span>
        {report.confidence_rationale && <span>{report.confidence_rationale}</span>}
      </div>

      {report.uncertainties.length > 0 && (
        <div className="report__block report__block--muted">
          <h4 className="report__subtitle">What we don't know</h4>
          <ul className="list list--muted">
            {report.uncertainties.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      )}
    </section>
  )
}
